#!/bin/bash -e
# /etc/init.d script for aeroo-docs
#

### BEGIN INIT INFO
# Provides:          office 
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO


. /lib/lsb/init-functions

EXECUTABLE=/usr/bin/aeroo-docs
PIDFILE=/var/run/aeroo-docs.pid

. /etc/aeroo-docs.conf

function start {
  echo "Starting Aeroo_docs server"
  $EXECUTABLE start
}

function stop {
  echo "Stopping Aeroo_docs server."
  $EXECUTABLE stop
}

function stop9 {
  echo "Stopping Aeroo_docs server."
  kill -9 $(cat $PIDFILE)
  rm -f $PIDFILE
}

case "$1" in
start)
  if [ -f $PIDFILE ]; then
    echo "Aeroo_docs server has already started."
    exit
  fi
  start
;;
stop)
  stop
;;
restart)
  stop
  start
;;
force-reload)
  stop9
  start
;;
*)
echo "Usage: $0 {start|stop|restart|force-reload}"
exit 1
esac
exit 0
