#!/bin/bash -e
# openoffice.org headless server script
#
# chkconfig: 2345 80 30
# description: headless openoffice server script
# processname: openoffice
#
# Author: Vic Vijayakumar
# Modified by Federico Ch. Tomasczik
# Modified by Luca Vercelli
#

### BEGIN INIT INFO
# Provides:          office 
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO


. /lib/lsb/init-functions

OOo_HOME=/usr/bin
SOFFICE_PATH=$OOo_HOME/soffice
PIDFILE=/var/run/openoffice-server.pid


function start {
  echo "Starting OpenOffice headless server"
  $SOFFICE_PATH --headless --nologo --nofirststartwizard --accept="socket,host=127.0.0.1,port=8100;urp" & > /dev/null 2>&1
  echo $! > $PIDFILE
}

function stop {
  echo "Stopping OpenOffice headless server."
  killall soffice && killall soffice.bin
  rm -f $PIDFILE
}

function stop9 {
  echo "Stopping OpenOffice headless server."
  killall -9 soffice && killall -9 soffice.bin
  rm -f $PIDFILE
}

case "$1" in
start)
  if [ -f $PIDFILE ]; then
    echo "OpenOffice headless server has already started."
    exit
  fi
  start
;;
stop)
  stop
;;
restart)
  stop
  start
;;
force-reload)
  stop9
  start
;;
*)
echo "Usage: $0 {start|stop|restart|force-reload}"
exit 1
esac
exit 0
